version: '3'

services:

  mongo_db:
    container_name: mongo_db
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  java_app:
    container_name: java_app
    image: entries_management:1.0.0
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "mongo_db"

volumes:
  mongo-data: